#!/bin/zsh

umask 0002

typeset -U path
path=(~/bin ~/local/bin /usr/local/bin $path)

export EDITOR=vim

if [ $(uname) = 'Darwin' ]; then
  export JAVA_HOME=`/usr/libexec/java_home`
fi

if [ -n DISPLAY ]; then
  export DISPLAY=:0.0
fi

# Quick `which` function for starting up
__has() {
    [[ -e "/usr/local/bin/$1" || -e "/usr/bin/$1" ]]
}
