#!/bin/zsh

if __which gdircolors; then
  eval `gdircolors -b`
elif __which dircolors; then
  eval `dircolors -b`
else
  echo_warn "No dircolors command found"
fi

watch=(notme)
WATCHFMT='%n %a at %t %w from %M'

REPORTTIME=2                # report time if execution exceeds amount of seconds
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory extendedglob nomatch notify
unsetopt autocd beep
bindkey -e
bindkey ' ' magic-space    # also do history expansion on space
bindkey '^I' complete-word # complete on tab, leave expansion to _expand

# http://xanana.ucsc.edu/~wgscott/wordpress_new/wordpress/?p=12
typeset -ga preexec_functions
typeset -ga precmd_functions
typeset -ga chpwd_functions
