#!/bin/zsh

p () {
    PROMPT=`eval 'echo $PROMPT_'$1`
}

cd.. () {
    cd `..n $1`
}

..n () {
    DOTS='..'
    for ((NUM=1; NUM<$1; NUM+=1)); do
        DOTS="$DOTS/.."
    done
    echo $DOTS
}

winip () {
    nmblookup $1 | head -n 2 | grep "^[0-9]" | sed "s/^\([0-9.]*\) .*$/\1/"
}

crypt() {
    echo "$@" | gpg -c | base64
}

decrypt() {
    echo "$@" | base64 -d | gpg -d
}

gits () {
    git stash && git $* && git stash pop
}

_git_list_branches () {
  for B in `git branch | sed -E 's/[\* ]+(.*)/\1/'`; do
    echo $B
  done
}

_gitco () {
  branches=( $(_git_list_branches) )
  _multi_parts / branches
}

compdef -p _gitco git co
