#!/bin/zsh

# global
DOTS="..."
for ((NUM=2; NUM<=10; NUM+=1)); do
#    alias -g "..$NUM"=`..n $NUM`
    alias -g $DOTS=`..n $NUM`
    DOTS="$DOTS."
done

#alias -g '...'='..1'
#alias -g '....'='..2'
#alias -g '.....'='..3'

# ls
if [ $(uname) = 'Darwin' ]; then
  if __has gls; then
    alias ls='gls -F --color'
  else
    echo_warn "On Darwin and 'gls' not found"
    alias ls='ls -Gp'
  fi
else
  alias ls='ls -F --color=auto'
fi

alias ll='ls -l'
alias la='ls -a'

# List only directories and symbolic
# links that point to directories
alias lsd='ls -d *(-/DN)'
alias lld='ls -ld *(-/DN)'

# List only file beginning with "."
alias lsa='ls -d .*'
alias lla='ls -ld .*'

alias lsr='ls -d **/*(.)'
alias llr='ls -ld **/*(.)'

alias lsdr='ls -d **/*(/)'
alias lldr='ls -ld **/*(/)'

# Standard stuff
alias mv='nocorrect mv'       # no spelling correction on mv
alias cp='nocorrect cp'       # no spelling correction on cp
alias mkdir='nocorrect mkdir' # no spelling correction on mkdir

alias j=jobs
alias pu=pushd
alias po=popd
alias d='dirs -v'
alias h=history

# application overrides
# alias grep=egrep
alias vi=vim

if [ $(uname) = 'Darwin' ]; then
  if __has mvim; then
    alias vim='mvim -v'
    EDITOR='mvim -v'
  fi
elif __has apt-get; then
  alias apti='sudo apt-get update && sudo apt-get install'
fi

alias sudovim=sudo\ vim
alias sudovi=sudovim
alias suvi=sudovim

autoload zmv
# Easy "mass move" alias
alias mmv='noglob zmv -W'

# http://www.jukie.net/bart/blog/screen-ssh-agent
_ssh_auth_save() {
    mkdir -p "$HOME/.screen"
    ln -sf "$SSH_AUTH_SOCK" "$HOME/.screen/ssh-auth-sock.$HOST"
}
alias screen='_ssh_auth_save && HOST="$HOST" screen'

# iTerm2 tab color commands
# http://code.google.com/p/iterm2/wiki/ProprietaryEscapeCodes
tab-color() {
    echo -ne "\033]6;1;bg;red;brightness;$1\a"
    echo -ne "\033]6;1;bg;green;brightness;$2\a"
    echo -ne "\033]6;1;bg;blue;brightness;$3\a"
}
tab-red() { tab-color 255 0 0 }
tab-green() { tab-color 0 255 0 }
tab-blue() { tab-color 0 0 255 }
tab-reset() { echo -ne "\033]6;1;bg;*;default\a" }

tab-exec() {
    trap "tab-reset" EXIT INT
    $1
    shift
    $*
}
color-ssh() {
    if [[ -n "$ITERM_SESSION_ID" ]]; then
        trap "tab-reset" INT EXIT
        if [[ "$*" =~ "production|ec2-.*compute-1" ]]; then
            tab-color 255 0 0
        else
            tab-color 0 255 0
        fi
    fi
    ssh $*
}
compdef _ssh color-ssh=ssh
alias ssh=color-ssh
