#!/bin/sh -ex

mkdir -p bundle
[ ! -d bundle/vundle ] && rm -rf bundle/* && git clone https://github.com/gmarik/vundle.git bundle/vundle
vim -u bundles.vim +BundleInstall +qall
(cd bundle/command-t && rake make)
